runtime: java
env: flex
runtime_config:
  jdk: openjdk8
  server: jetty9
service: bankapp1

handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
